
resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowType: COUNT_BASED
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 10
      waitDurationInOpenState: 30000 # ?? ??? ???? ??, ?? ???? ??? ??? ????.
      failureRateThreshold: 30 # ??? ??? ?? ???(???)?? ? ?? ???? ??? ???.
      eventConsumerBufferSize: 10
      registerHealthIndicator: true # actuator ?? ??? ?? ??
      ignore-exceptions:
        - java.lang.IllegalStateException
  instances:
    testApi:
      baseConfig: default

management:
  endpoints:
    web:
      exposure:
        include:
          - "*" # ???? ?? actuator ?? ??

  health:
    circuitbreakers:
      enabled: true # circuitbreakers ?? ??
